site_name: thefriendlystars
site_url: https://zkbt.github.com/thefriendlystars
nav:
    - Welcome: index.md
    - installation.ipynb
    - gaia.ipynb
theme:
  name: "material"
  features:
      - navigation.tracking
repo_url: https://github.com/zkbt/thefriendlystars/
plugins:
  - search
  - mkdocs-jupyter:
      execute : True
      include_source : True
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [../thefriendlystars]
          selection:
            docstring_style: "numpy"
          rendering:
            show_source: True
            show_root_heading: True
            show_root_toc_entry: False
            show_root_full_path: False
            show_category_heading: False
            show_submodules: False
            merge_init_into_class: False
            show_if_no_docstring: False
            heading_level: 3
            show_bases: False
      custom_templates: templates
  - exclude:
      glob:
        - "*.pdf"
        - "*.fits"
        - "*.npy"
markdown_extensions:
    - toc:
        permalink: "#"

# this is super borrowed from Christina Hedges' fabulous
# https://christinahedges.github.io/astronomy_workflow/
